import React, {useState} from 'react';
import { v4 as uuidv4 } from 'uuid';
import Head from "next/head";
import Main from "@/components/pageWraper/main";
import ViewHeader from "@/components/viewElements/viewHeader";
import ViewColumn from "@/components/viewElements/viewColumn";
import ViewNameBlock from "@/components/viewElements/viewNameBlock";
import ViewBlock from "@/components/viewElements/viewBlock";
import {Formik} from "formik";
// import {useRouter} from "next/router";

const FormConstructor = () => {

    // const router = useRouter()
    // const {formId} = router.query

    const [formObject, setFormObject] = useState({
        id: uuidv4(),
        creator: "test",
        active: true,
        formName: "New form",
        formDescription: "Description",
        questions: [{
            id: uuidv4(),
            required: false,
            type: "oneLineText",
            question: "test1",
            options:[]
        },
            {
                required: false,
                type: "paragraphText",
                question: "test2",
                options:[]
            },
            {
                required: false,
                type: "radio",
                question: "test3",
                options:[{
                    id: uuidv4(),
                    text: "444"
                },{
                    id: uuidv4(),
                    text: "4441"
                },{
                    id: uuidv4(),
                    text: "4442"
                },{
                    id: uuidv4(),
                    text: "4443"
                }]
            },
            {
                required: false,
                type: "checkbox",
                question: "test4",
                options:[{
                    id: uuidv4(),
                    text: "444"
                },{
                    id: uuidv4(),
                    text: "4441"
                },{
                    id: uuidv4(),
                    text: "4442"
                },{
                    id: uuidv4(),
                    text: "4443"
                }]
            },
            {
                required: false,
                type: "select",
                question: "test5",
                options:[{
                    id: uuidv4(),
                    text: "444"
                },{
                    id: uuidv4(),
                    text: "4441"
                },{
                    id: uuidv4(),
                    text: "4442"
                },{
                    id: uuidv4(),
                    text: "4443"
                }]
            },
            {
                required: false,
                type: "date",
                question: "test6",
                options:[]
            },
            {
                required: false,
                type: "time",
                question: "test7",
                options:[]
            }]
    })


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Formik
                initialValues={{
                    test: [],
                }}
                onSubmit={async (values) => {
                    alert(JSON.stringify(values, null, 2));
                }}
            >{() => (
                <>
                    <ViewHeader id={formObject.id}/>
                    <Main>
                        <ViewColumn>
                            <ViewNameBlock
                                formName={formObject.formName}
                                formDescription={formObject.formDescription}
                            />
                            {
                                formObject.questions.map((question , index) => (
                                    <ViewBlock
                                        key={index}
                                        question={question}
                                    />
                                ))
                            }
                        </ViewColumn>
                    </Main>
                </>
            )}
        </Formik>
        </>
    );
};

export default FormConstructor;

