import React from 'react';
import Head from "next/head";
import Main from "@/components/pageWraper/main";
import ConstructorHeader from "@/components/constructorElements/constructorHeader";
import ConstructorColumn from "@/components/constructorElements/constructorColumn";
import ConstructorNameBlock from "@/components/constructorElements/constructorNameBlock";

const FormConstructor = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ConstructorHeader/>
            <Main>
                <ConstructorColumn>
                    <ConstructorNameBlock/>
                </ConstructorColumn>
            </Main>
        </>
    );
};

export default FormConstructor;