import React, {useState} from 'react';
import { v4 as uuidv4 } from 'uuid';
import Head from "next/head";
import Main from "@/components/pageWraper/main";
import ConstructorHeader from "@/components/constructorElements/constructorHeader";
import ConstructorColumn from "@/components/constructorElements/constructorColumn";
import ConstructorNameBlock from "@/components/constructorElements/constructorNameBlock";
import ConstructorBlock from "@/components/constructorElements/constructorBlock";

const FormConstructor = () => {

    const formCredentials = {
        id: uuidv4(),
        creator: "test",
        active: true,
        formName: "",
        formDescription: "",
    }

    const [questions, setQuestions] = useState([{
        id: uuidv4(),
        required: false,
        type: "radio",
        question:"",
        options:[{
            id: uuidv4(),
            text: ""
        }]
    }])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ConstructorHeader formObject={formCredentials}/>
            <Main>
                <ConstructorColumn>
                    <ConstructorNameBlock formName={formCredentials}/>
                    {
                        questions.map((q) => (
                            <ConstructorBlock
                                id={q.id}
                                key={q.id}
                                questionsObject={questions}
                                updater={setQuestions}
                                />
                        ))
                    }
                </ConstructorColumn>
            </Main>
        </>
    );
};

export default FormConstructor;