import Head from 'next/head'
import Header from "@/components/pageWraper/header";
import Main from "@/components/pageWraper/main";
import Footer from "@/components/pageWraper/footer";
import About from "@/components/about";
export default function Welcome() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header></Header>
        <Main>
          <About></About>
        </Main>
        <Footer></Footer>
    </>
  )
}
