import React from 'react';
import Head from "next/head";
import LoginForm from "@/components/login/loginForm";

const Login = () => {
    return (
        <>
            <Head>
                <title>ReportGenerator: Sign in</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LoginForm></LoginForm>
        </>
    );
};

export default Login;