import React from 'react';
import Head from "next/head";
import LoginForm from "@/components/login/loginForm";
import {useSession} from "next-auth/react";
import {useRouter} from "next/router";

const Login = () => {
    const {status} = useSession()
    const router = useRouter()
    if (status === "authenticated") {
        router.push("/home")
    }
    return (
        <>
            <Head>
                <title>ReportGenerator: Sign in</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LoginForm></LoginForm>
        </>
    );
};

export default Login;