import React from 'react';
import Head from "next/head";
import RegisterForm from "@/components/login/registerForm";
import {useSession} from "next-auth/react";
import {useRouter} from "next/router";

const Register = () => {
    const {status} = useSession()
    const router = useRouter()
    if (status === "authenticated") {
        router.push("/home")
    }
    return (
        <>
            <Head>
                <title>ReportGenerator: Register</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <RegisterForm></RegisterForm>
        </>
    );
};

export default Register;