import React from "react";
import {v4 as uuidv4} from "uuid";
import Head from "next/head";
import ConstructorHeader from "@/components/constructorElements/constructorHeader";
import Main from "@/components/pageWraper/main";
import StatisticColumn from "@/components/statisticElements/statisticColumn";
import StatisticNameBlock from "@/components/statisticElements/statisticNameBlock";
import StatisticBlock from "@/components/statisticElements/statisticBlock";
const FormConstructor = () => {

    // const router = useRouter()
    // const {formId} = router.query

    const formObject = [{
        type: "oneLineText",
        question: "testtesttesttest",
        answers: ["123", "123", "123", "321", "321"]
    },
    {
        type: "checkbox",
        question: "testtesttesttest",
        answers: ["123", "123", "123", "321", "321"]
    },
    {
        type: "radio",
        question: "testtesttesttest",
        answers: ["123", "123", "123", "321", "321"]
    }]

    function handleFormSubmit(){
        console.log(formObject)
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ConstructorHeader onFormSubmit={handleFormSubmit}/>
            <Main>
                <StatisticColumn>
                    <StatisticNameBlock answersCount={"12"}/>
                    {
                        formObject.map((question, index) => (
                            <StatisticBlock
                                key={index}
                                question={question}
                            />
                        ))
                    }
                </StatisticColumn>
            </Main>
        </>
    );
};

export default FormConstructor;